version: 2.1

executors:
  coq-810:
    docker:
      - image: coqorg/coq:8.10.2

  coq-811:
    docker:
      - image: coqorg/coq:8.11.0

  haskell:
    docker:
      - image: fpco/stack-build:lts

  haskell-with-coq-810:
    docker:
      - image: fpco/stack-build:lts
      - image: coqorg/coq:8.10.2
        environment:
          COQ_VERSION: 8.10.2
          SSREFLECT_VERSION: 1.9.0

  haskell-with-coq-811:
    docker:
      - image: fpco/stack-build:lts
      - image: coqorg/coq:8.11.0
        environment:
          COQ_VERSION: 8.11.0
          SSREFLECT_VERSION: 1.10.0

commands:
  build-base:
    steps:
      - run: |
          eval $(opam config env)
          make -C base
          make -C base-thy

  build-transformers:
    steps:
      - run: |
          eval $(opam config env)
          make -C examples/transformers/lib

  build-containers:
    steps:
      - run: |
          eval $(opam config env)
          opam list -i coq-mathcomp-ssreflect.${SSREFLECT_VERSION} --silent || opam install -y coq-mathcomp-ssreflect.${SSREFLECT_VERSION}
          make -C examples/containers/lib
          make -C examples/containers/theories

  build-ghc:
    steps:
      - run: |
          eval $(opam config env)
          opam list -i coq-mathcomp-ssreflect.${SSREFLECT_VERSION} --silent || opam install -y coq-mathcomp-ssreflect.${SSREFLECT_VERSION}
          make -C examples/ghc/lib
          make -C examples/ghc/theories
          make -C examples/core-semantics

  build-others:
    steps:
      - run: |
          eval $(opam config env)
          make -C examples/successors
          make -C examples/compiler
          make -C examples/rle
          make -C examples/bag
          make -C examples/quicksort
          make -C examples/dlist
          make -C examples/intervals
          make -C examples/coinduction

  build-tests:
    steps:
      - run: |
          eval $(opam config env)
          make -C examples/tests
          make -C examples/base-tests

  checkout-with-sub:
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

jobs:
  build:
    executor: haskell
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - hs-to-coq-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: |
            stack --no-terminal --install-ghc test --only-dependencies
            stack --no-terminal --install-ghc install QuickCheck HUnit test-framework test-framework-hunit test-framework-quickcheck2
      - run:
          name: Build hs-to-coq
          command: stack --no-terminal --install-ghc install
      - save_cache:
          name: Cache Dependencies
          key: hs-to-coq-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - persist_to_workspace:
          root: .
          paths:
            - .stack-work

  coq-810-base:
    executor: coq-810
    steps:
      - checkout
      - build-base
      - persist_to_workspace:
          root: .
          paths:
            - base
            - base-thy

  coq-810-transformers:
    executor: coq-810
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - build-transformers
      - persist_to_workspace:
          root: examples
          paths:
            - transformers

  coq-810-containers:
    executor: coq-810
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - opam-coq.8.10.2
      - build-containers
      - persist_to_workspace:
          root: examples
          paths:
            - containers
      - save_cache:
          name: Cache Dependencies
          key: opam-coq.8.10.2
          paths:
            - "/root/.opam"

  coq-810-ghc:
    executor: coq-810
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - opam-coq.8.10.2
      - build-ghc

  coq-810-others:
    executor: haskell-with-coq-810
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - hs-to-coq-{{ checksum "stack.yaml" }}
      - run: stack --no-terminal --install-ghc install
      - build-others

  coq-810-tests:
    executor: haskell-with-coq-810
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - hs-to-coq-{{ checksum "stack.yaml" }}
      - run: stack --no-terminal --install-ghc install
      - build-tests

  coq-811-base:
    executor: coq-811
    steps:
      - checkout
      - build-base
      - persist_to_workspace:
          root: .
          paths:
            - base
            - base-thy

  coq-811-transformers:
    executor: coq-811
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - build-transformers
      - persist_to_workspace:
          root: examples
          paths:
            - transformers

  coq-811-containers:
    executor: coq-811
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - opam-coq.8.11.0
      - build-containers
      - persist_to_workspace:
          root: examples
          paths:
            - containers
      - save_cache:
          name: Cache Dependencies
          key: opam-coq.8.11.0
          paths:
            - "/root/.opam"

  coq-811-ghc:
    executor: coq-811
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - opam-coq.8.11.0
      - build-ghc

  coq-811-others:
    executor: haskell-with-coq-811
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - hs-to-coq-{{ checksum "stack.yaml" }}
      - run: stack --no-terminal --install-ghc install
      - build-others

  coq-811-tests:
    executor: haskell-with-coq-811
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - hs-to-coq-{{ checksum "stack.yaml" }}
      - run: stack --no-terminal --install-ghc install
      - build-tests


workflows:
  version: 2

  hs-to-coq:
    jobs:
      - build
      - coq-810-base
      - coq-810-transformers:
          requires:
            - coq-810-base
      - coq-810-containers:
          requires:
            - coq-810-base
      - coq-810-ghc:
          requires:
            - coq-810-transformers
            - coq-810-containers
      - coq-810-others:
          requires:
            - build
            - coq-810-base
      - coq-810-tests:
          requires:
            - build
            - coq-810-base
      - coq-811-base
      - coq-811-transformers:
          requires:
            - coq-811-base
      - coq-811-containers:
          requires:
            - coq-811-base
      - coq-811-ghc:
          requires:
            - coq-811-transformers
            - coq-811-containers
      - coq-811-others:
          requires:
            - build
            - coq-811-base
      - coq-811-tests:
          requires:
            - build
            - coq-811-base
